### ISSUE TITLE
GameView Rotation

### ISSUE THREAD

**Issue by cthilhi** [kivy/kivent#103]
Hi, I was told to open an issue here about this:

There is no way to rotate the camera / GameView right now. 
Pretty self explainatory.. I just want to turn the camera without turning the whole world ;)

Thanks!

**Comment by Kovak** [comment]
Hi @cthilhi , thanks for opening this. Hopefully I will have a PR for you to test in the next week or so. I will make sure it is done before 2.2 release.

**Comment by udiboy1209** [comment]
@Kovak, can I work on this or have you already coded a solution?

**Comment by Kovak** [comment]
I have not done one yet, would love to see a solution for it :+1:

**Comment by udiboy1209** [comment]
Closed by #124
