### ISSUE TITLE
Issue when building docs

### ISSUE THREAD

**Issue by labuzm** [kivy/kivent#106]
I'm having hard time trying to build docs. KivEnt seems to work OK - all examples run without any problem, but when I run:

<code>make html</code>

from docs module it gives me this: https://gist.github.com/labuzm/b3dbf81fe02d12af3975
No matter if Kivent is build in place or if installed into virtualenv, any ideas?

**Comment by Kovak** [comment]
Getting sphinx to read all the cython is a bit tricky, I think everything has to be built in place and there may need to be some linking to be done. I'll work on automating more of this for the next release, and documenting any leftovers. In the meantime, you can access the docs online at: http://kivent.org/docs/index.html

**Comment by labuzm** [comment]
Thanks for the replay, yes, I've noticed that is not easy to make it work. I just wanted to test if importing dunder VERSION inside the docs/sources/conf.py (needed for #105) doesn't break anything.

**Comment by llfkj** [comment]
I noticed the same issue today. 

I ended up building everything in place (I needed to build *all* the modules using `cd module_name && python setup.py build_ext --inplace`) and then doing a `cd ../docs && make html`

It does seem a bit finicky.
