### ISSUE TITLE
GameView scaling boundaries

### ISSUE THREAD

**Issue by labuzm** [kivy/kivent#110]
GameView doesn't respect map size, it's possible to zoom out beyond map boundaries and this leads to strange flickering behavior when do_scroll_lock is set to True. How about adding something like do_zoom_lock or renaming do_scroll_lock and locking both zoom and scroll?

**Comment by udiboy1209** [comment]
@labuzm do_zoom_lock might cause problems when the game is running fullscreen and map size doesn't match.
