### ISSUE TITLE
a way to set 'CLAMP' mode on textures

### ISSUE THREAD

**Issue by labuzm** [kivy/kivent#111]
This will potentially fix the issue with non-seamless tiles rendering after scale is applied to the GameView.

**Comment by Kovak** [comment]
Clamp only works on individual images and most often you are going to want to be working with atlases for performance. The equivalent is increasing the padding when you create the atlas: https://kivy.org/docs/api-kivy.atlas.html#kivy.atlas.Atlas.create note the padding kwarg.
