### ISSUE TITLE
buildozer build issue

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/kivent#114]
Problem with building using buildozer, anyway, steps to reproduce:

1. mkdir ~/tmp/check

2. cd ~/tmp/check

3. mkvirtualenv tmpcheck

3. pip install cython

4. pip install git+https://github.com/tito/cymunk

5. pip install git+https://github.com/kivy/kivy@master

6. pip install buildozer

7. git clone -b old_toolchain --single-branch https://github.com/kivy/python-for-android p4a

8. git clone -b 2.2-dev https://github.com/kivy/kivent 

9. touch main.py

10. buildozer init

11. cp -v kivent/modules/recipes/kivent_core/recipe.sh p4a/recipes/kivent_core/recipe.sh

12. cp -v kivent/modules/recipes/kivent_cymunk/recipe.sh p4a/recipes/kivent_cymunk/recipe.sh

13. perl -pi -e 's/^requirements.*/requirements = kivent_core,kivent_cymunk,kivy/' buildozer.spec

14. VERSION_kivy=master P4A_kivent_core_DIR=~/tmp/check/kivent/modules/core/ P4A_kivent_cymunk_DIR=~/tmp/check/kivent/modules/cymunk/ APP_ANDROID_P4A_DIR=~/tmp/check/p4a/ buildozer --verbose android debug

Result: 

```
result:


Call build_kivent_core

Entering in ARM environment

Compiler found at /home/maho/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc

[INFO              ] [Logger      ] Record log in /home/maho/.kivy/logs/kivy-16-02-01-7.log

[INFO              ] [Kivy        ] v1.9.2-dev0

[INFO              ] [Python      ] v2.7.2 (default, Feb  1 2016, 13:21:49)

[GCC 4.9.2]

running build_ext

Traceback (most recent call last):

  File "setup.py", line 5, in <module>

    import kivy

ImportError: No module named kivy

# Command failed: ./distribute.sh -m "kivent_core kivent_cymunk kivy" -d "myapp"

#

# Buildozer failed to execute the last command

# The error might be hidden in the log above this error

# Please read the full log, and search for it before

# raising an issue with buildozer itself.

# In case of a bug report, please add a full log with log_level = 2
```

**Comment by Tadanodaemon** [comment]
I am having the same exact issue. Is there any other methods I could use to package this into an apk for android?

**Comment by mahomahomaho** [comment]
I had a thought, that maybe reason is that kivy now is 1.9.2 in master, and I should use 1.9.1, so I changed step 6 to  "pip install git+https://github.com/kivy/kivy@1.9.1" and step 15 to
 
 VERSION_kivy=1.9.1 P4A_kivent_core_DIR=~/tmp/check/kivent/modules/core/ P4A_kivent_cymunk_DIR=~/tmp/check/kivent/modules/cymunk/ APP_ANDROID_P4A_DIR=~/tmp/check/p4a/ buildozer --verbose android debug

and now I have following error:


[....]
copying examples/kv/app_stencil.kv -> /home/maho/tmp/check/p4a/build/python-install/share/kivy-examples/kv
running install_egg_info
Writing /home/maho/tmp/check/p4a/build/python-install/lib/python2.7/site-packages/Kivy-1.9.1-py2.7.egg-info
Leaving ARM environment
Call build_kivent_core
Entering in ARM environment
Compiler found at /home/maho/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin//arm-linux-androideabi-gcc
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
# Command failed: ./distribute.sh -m "kivent_core kivent_cymunk kivy" -d "myapp"
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by Kovak** [comment]
All the build scripts technically need to be rewritten for the new P4A. This will probably happen instead of trying to get the old p4a working again.

**Comment by mahomahomaho** [comment]
Dnia 29 kwietnia 2016 18:48:27 CEST, Kovak <notifications@github.com> napisał(a):
>All the build scripts technically need to be rewritten for the new P4A.
>This will probably happen instead of trying to get the old p4a working
>again.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kivy/kivent/issues/114#issuecomment-215803678

is any work in progress re new p4a or i should start from beginning? is bulldozer able to use new p4a? 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kovak** [comment]
In buildozer I believe it is the android_new target instead of just android. The new recipes I believe are now python scripts, I haven't started yet. Take a look at the recipes in the master branch of buildozer to get an idea of what a new style recipe would look like.
