### ISSUE TITLE
impossible to install on win7 64 python 3.4

### ISSUE THREAD

**Issue by lenivaya10001** [kivy/kivent#122]
even after trick from internet stackoverflow
for vc++2010express (install sdk and patch it)
create fatal error... installer can not find file renderers.c... in unzipped path from github i can find only renderers.pyx renderers.pxd files.... something wrong

**Comment by Kovak** [comment]
We typically do not use VC to compile Kivy or Kivent instead favoring mingw. 

Make sure to have all the kivy windows dev dependencies installed, and then you should be able to install kivent.
