### ISSUE TITLE
Can one use kivent_cymunk as a standalone library?

### ISSUE THREAD

**Issue by maroxe** [kivy/kivent#139]
Hello guys,

Terrific job on developing kivent! 

I wanted to know if the module kivent_cymunk can be used independently of the rest of the library, and if so, how?

thanks!

**Comment by Kovak** [comment]
You can use the cymunk module its based on standalone

**Comment by maroxe** [comment]
I see, thank you!

To deploy your app, you just add the folder containing cymunk and you're good to go? (with py4andorid / kivy-ios) or is there something special to do?

I apologize for my basic quesitons, I have never developed mobile apps before.

**Comment by Kovak** [comment]
There is a py4a recipe for cymunk. So you add it to the buildozer.spec requirements and it should be picked up. Not certain how kivy-ios works.

**Comment by maroxe** [comment]
That works, thanks!

I am trying to make it work with iOS, the problem seem to be that cymunk's setup.py  doesn't generate a lib*.a, but only a .so. Would you know why would that be?

**Comment by Kovak** [comment]
It may be somewhat similar to the issue here (IE we do not always set all the compile flags correctly, I just got an iOS device a few days ago but haven't had a chance to look into things on iOS yet):

https://github.com/kivy/kivent/pull/132
