### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by fy0** [kivy/kivent#15]
building 'kivent' extension
E:\Cloud\Kivy-1.8.0-py2.7-win32\MinGW\bin\gcc.exe -mno-cygwin -mdll -O -Wall -IE
:\Cloud\Kivy-1.8.0-py2.7-win32\Python27\include -IE:\Cloud\Kivy-1.8.0-py2.7-win3
2\Python27\PC -c kivent\__init__.c -o build\temp.win32-2.7\Release\kivent\__init
__.o -std=c99 -ffast-math
kivent\__init__.c:2786: warning: useless keyword or type name in empty declarati
on
kivent\__init__.c:2786: warning: empty declaration
kivent\__init__.c:2788: warning: useless keyword or type name in empty declarati
on
kivent\__init__.c:2788: warning: empty declaration
kivent\__init__.c:2791: warning: useless keyword or type name in empty declarati
on
kivent\__init__.c:2791: warning: empty declaration
kivent\__init__.c:2793: warning: useless keyword or type name in empty declarati
on
kivent\__init__.c:2793: warning: empty declaration
kivent\__init__.c: In function `__pyx_pf_6kivent_15ParticleManager_22update':
kivent\__init__.c:30789: error: `M_PI_2' undeclared (first use in this function)

kivent\__init__.c:30789: error: (Each undeclared identifier is reported only onc
e
kivent\__init__.c:30789: error: for each function it appears in.)
kivent\__init__.c: In function `__pyx_pf_6kivent_13CymunkPhysics_22create_compon
ent':
kivent\__init__.c:34732: error: `M_PI_2' undeclared (first use in this function)

error: command 'gcc' failed with exit status 1

M_PI_2 not found.
Compiler is gcc-tdm.

And when I try to run sample app, I got:
Fatal Python error: (pygame parachute) Segmentation Fault

btw: Suggest to add spine support, it's a 2d animation tool.

**Comment by Kovak** [comment]
we've had windows support for awhile thanks to @chozabu closing this
