### ISSUE TITLE
Please provide pip installable archive

### ISSUE THREAD

**Issue by harbdog** [kivy/kivent#150]
Would it be possible to provide us a way to install kivent easily from a single command using pip?

Similar to how your documentation says to install cymunk would be awesome, e.g.:
`pip install https://github.com/tito/cymunk/archive/master.zip`

**Comment by udiboy1209** [comment]
Kivent is currently split into multiple modules which are in the same repository so we can't make the repository pip installable. We are planning to split these modules into their own repositories so they can be easily updated independently and installed via pip. For now you can use this script: [kivent-install.sh](https://gist.github.com/udiboy1209/60f08dbf4d6e90d23ac38d9a8f863c29)

**Comment by udiboy1209** [comment]
I had forgotten about these scripts in the repo: https://github.com/kivy/kivent/tree/2.2-dev/scripts . You can use either!
