### ISSUE TITLE
building on osx10.9.2 with xcode 5.1.1 required 3 files from kivy/graphics

### ISSUE THREAD

**Issue by gJigsaw** [kivy/kivent#16]
/kivy/kivy/graphics/common_subset.h
/kivy/kivy/graphics/gl2platform.h
/kivy/kivy/graphics/khrplatform.h

Once I'd sym-linked these into 

KivEnt/kivent/kivent/

then my build worked.

**Comment by Kovak** [comment]
this should be fixed with the upcoming release of kivy 1.9.1 and kivent 2.1
