### ISSUE TITLE
Tilemap.tiles is empty list

### ISSUE THREAD

**Issue by spinningD20** [kivy/kivent#187]
Hi guys!  I've been testing building pathfinding grids to work kivent into my current game project, and would love to have access to the 2d array of tiles.  I'm not sure what's wrong and why it's an empty list, but I've tested on a couple maps and it seems like a bug.

**Comment by udiboy1209** [comment]
@spinningD20 check the above commit. Was a stupid missing return statement :stuck_out_tongue:
