### ISSUE TITLE
Non-square dimension tilemaps not supported

### ISSUE THREAD

**Issue by spinningD20** [kivy/kivent#188]
Hi again!  I ran across another limitation, where loading the map is based off of width only, height mirrored from that, which supports only square shaped maps.  Any chance we can add support for mismatched height/width maps (example, 20x40, 35x42, etc)?

Thanks!

**Comment by udiboy1209** [comment]
@spinningD20 if you are using a tmx file for loading the map, it should automatically load non-square width and height from the tmx file. If you are creating one yourself, you can set the `tile_size` property of the `tile_map` to set tile width and height to anything you like. [check ref](https://github.com/kivy/kivent/blob/2.2-dev/modules/maps/kivent_maps/map_data.pyx#L492). 

I'm pretty sure this would work because staggered and hexagonal tile maps require different tile dimensions, and this property is used by that too.

**Comment by spinningD20** [comment]
I might be misunderstanding, but all of the example maps have square dimensions (10x10, etc) even if they are staggered.  I tested this by simply adding one row or column in Tiled to the tmx map, filling it in with tiles and saving / running the example.  It crashes.

**Comment by udiboy1209** [comment]
It may be a bug then. I'm pretty sure this feature is implemented. I'll look into it soon!

**Comment by udiboy1209** [comment]
@spinningD20 The tile size in the tileset image may be square for staggered/isometric/hexagonal but while rendering, the maps module considers it as non-square. You can check by printing map.tile_size for each of these maps from the examples, they are all non-square. For eg. isometric map has (128,64) tile size. If the module considered them square, you would see gaps like you see in the [tileset image](https://github.com/kivy/kivent/blob/2.2-dev/examples/assets/maps/basic_ground_tiles.png).

This may also just be a bug with orthogonal maps, but for that I'd need to see your error log and possibly the example you used.

**Comment by spinningD20** [comment]
I can upload an example but it would be easier for you to add a row to the existing isometric example map to test. I'm not talking about tile size, I'm talking map size, map dimensions. Ten tiles by ten tiles is okay, ten tiles by eleven tiles is not, for example.

**Comment by udiboy1209** [comment]
@spinningD20 Ahh okay I got your problem now! The code section you refer to is not the bug, height is being calculated correctly in the expression below. I think I have messed up x,y coords and row,col indexing somewhere in the code which is causing this. It'll take me a while to figure it out. Thanks for reporting this!

**Comment by spinningD20** [comment]
No problem, sorry it wasn't coming out clearly!  I'll keep my testing maps square for now, no big deal, just wasn't sure how to fix it and wanted to let you know.

Thanks again!

**Comment by udiboy1209** [comment]
Should be fixed by #192 . Tell me on this issue if you are still facing problems @spinningD20 and we'll reopen this.
