### ISSUE TITLE
Kivent Core Compilation

### ISSUE THREAD

**Issue by jupart** [kivy/kivent#189]
Ubuntu 16.04, fresh install of Kivy, fails compilation on "from kivy.graphics.c_opengl cimport GLfloat, GLubyte"

$ sudo python3 setup.py build_ext install
[INFO   ] [Logger      ] Record log in /home/jpartain/.kivy/logs/kivy_17-01-19_23.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
missing cimport in module 'kivy.graphics.c_opengl': ./kivent_core/rendering/batching.pxd
missing cimport in module 'kivy.graphics.c_opengl': ./kivent_core/rendering/fixedvbo.pxd
missing cimport in module 'kivy.graphics.c_opengl': ./kivent_core/rendering/vertex_formats.pxd
missing cimport in module 'kivy.graphics.c_opengl': kivent_core/rendering/batching.pyx
missing cimport in module 'kivy.graphics.c_opengl': kivent_core/rendering/batching.pxd
missing cimport in module 'kivy.graphics.c_opengl': kivent_core/rendering/model.pyx
missing cimport in module 'kivy.graphics.c_opengl': kivent_core/rendering/gl_debug.pyx
missing cimport in module 'kivy.graphics.c_opengl': kivent_core/rendering/fixedvbo.pyx
missing cimport in module 'kivy.graphics.c_opengl': kivent_core/rendering/fixedvbo.pxd
missing cimport in module 'kivy.graphics.c_opengl': kivent_core/systems/renderers.pyx
missing cimport in module 'kivy.graphics.c_opengl': kivent_core/rendering/vertex_format.pyx
missing cimport in module 'kivy.graphics.c_opengl': kivent_core/rendering/vertex_formats.pxd
Compiling kivent_core/systems/animation.pyx because it changed.
Compiling kivent_core/memory_handlers/zonedblock.pyx because it changed.
Compiling kivent_core/systems/color_systems.pyx because it changed.
Compiling kivent_core/rendering/batching.pyx because it changed.
Compiling kivent_core/uix/cwidget.pyx because it changed.
Compiling kivent_core/systems/gameview.pyx because it changed.
Compiling kivent_core/memory_handlers/utils.pyx because it changed.
Compiling kivent_core/rendering/cmesh.pyx because it changed.
Compiling kivent_core/systems/rotate_systems.pyx because it changed.
Compiling kivent_core/systems/staticmemgamesystem.pyx because it changed.
Compiling kivent_core/rendering/frame_objects.pyx because it changed.
Compiling kivent_core/systems/position_systems.pyx because it changed.
Compiling kivent_core/rendering/model.pyx because it changed.
Compiling kivent_core/managers/sound_manager.pyx because it changed.
Compiling kivent_core/managers/system_manager.pyx because it changed.
Compiling kivent_core/memory_handlers/pool.pyx because it changed.
Compiling kivent_core/rendering/gl_debug.pyx because it changed.
Compiling kivent_core/managers/resource_managers.pyx because it changed.
Compiling kivent_core/memory_handlers/tests.pyx because it changed.
Compiling kivent_core/rendering/animation.pyx because it changed.
Compiling kivent_core/uix/gamescreens.pyx because it changed.
Compiling kivent_core/systems/gamesystem.pyx because it changed.
Compiling kivent_core/rendering/fixedvbo.pyx because it changed.
Compiling kivent_core/systems/gamemap.pyx because it changed.
Compiling kivent_core/systems/renderers.pyx because it changed.
Compiling kivent_core/rendering/vertex_format.pyx because it changed.
Compiling kivent_core/memory_handlers/indexing.pyx because it changed.
Compiling kivent_core/memory_handlers/zone.pyx because it changed.
Compiling kivent_core/memory_handlers/block.pyx because it changed.
Compiling kivent_core/systems/scale_systems.pyx because it changed.
Compiling kivent_core/rendering/svg_loader.pyx because it changed.
Compiling kivent_core/systems/lifespan.pyx because it changed.
Compiling kivent_core/rendering/vertex_formats.pyx because it changed.
Compiling kivent_core/memory_handlers/membuffer.pyx because it changed.
[ 1/34] Cythonizing kivent_core/managers/resource_managers.pyx
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 from kivy.graphics.c_opengl cimport GLfloat, GLubyte
 ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:1:0: 'kivy/graphics/c_opengl.pxd' not found
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 from kivy.graphics.c_opengl cimport GLfloat, GLubyte
 ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:1:0: 'kivy/graphics/c_opengl/GLfloat.pxd' not found
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 from kivy.graphics.c_opengl cimport GLfloat, GLubyte
 ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:1:0: 'kivy/graphics/c_opengl/GLubyte.pxd' not found
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 from kivy.graphics.c_opengl cimport GLfloat, GLubyte
 
 ctypedef struct VertexFormat4F:
     GLfloat[2] pos
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:4:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 from kivy.graphics.c_opengl cimport GLfloat, GLubyte
 
 ctypedef struct VertexFormat4F:
     GLfloat[2] pos
     GLfloat[2] uvs
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:5:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 ctypedef struct VertexFormat4F:
     GLfloat[2] pos
     GLfloat[2] uvs
 
 ctypedef struct VertexFormat7F:
     GLfloat[2] pos
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:8:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     GLfloat[2] pos
     GLfloat[2] uvs
 
 ctypedef struct VertexFormat7F:
     GLfloat[2] pos
     GLfloat[2] uvs
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:9:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     GLfloat[2] uvs
 
 ctypedef struct VertexFormat7F:
     GLfloat[2] pos
     GLfloat[2] uvs
     GLfloat rot
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:10:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 
 ctypedef struct VertexFormat7F:
     GLfloat[2] pos
     GLfloat[2] uvs
     GLfloat rot
     GLfloat[2] center
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:11:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     GLfloat[2] uvs
     GLfloat rot
     GLfloat[2] center
 
 ctypedef struct VertexFormat4F4UB:
     GLfloat[2] pos
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:14:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     GLfloat rot
     GLfloat[2] center
 
 ctypedef struct VertexFormat4F4UB:
     GLfloat[2] pos
     GLfloat[2] uvs
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:15:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     GLfloat[2] center
 
 ctypedef struct VertexFormat4F4UB:
     GLfloat[2] pos
     GLfloat[2] uvs
     GLubyte[4] v_color #we don't want to clash with Kivy's 'color' uniform
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:16:4: 'GLubyte' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     GLfloat[2] pos
     GLfloat[2] uvs
     GLubyte[4] v_color #we don't want to clash with Kivy's 'color' uniform
 
 ctypedef struct VertexFormat2F4UB:
     GLfloat[2] pos
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:19:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     GLfloat[2] uvs
     GLubyte[4] v_color #we don't want to clash with Kivy's 'color' uniform
 
 ctypedef struct VertexFormat2F4UB:
     GLfloat[2] pos
     GLubyte[4] v_color
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:20:4: 'GLubyte' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 ctypedef struct VertexFormat2F4UB:
     GLfloat[2] pos
     GLubyte[4] v_color
 
 ctypedef struct VertexFormat7F4UB:
     GLfloat[2] pos
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:23:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     GLfloat[2] pos
     GLubyte[4] v_color
 
 ctypedef struct VertexFormat7F4UB:
     GLfloat[2] pos
     GLfloat[2] uvs
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:24:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
     GLubyte[4] v_color
 
 ctypedef struct VertexFormat7F4UB:
     GLfloat[2] pos
     GLfloat[2] uvs
     GLfloat rot
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:25:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 
 ctypedef struct VertexFormat7F4UB:
     GLfloat[2] pos
     GLfloat[2] uvs
     GLfloat rot
     GLfloat[2] center
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:26:4: 'GLfloat' is not a type identifier
 
 Error compiling Cython file:
 ------------------------------------------------------------
 ...
 ctypedef struct VertexFormat7F4UB:
     GLfloat[2] pos
     GLfloat[2] uvs
     GLfloat rot
     GLfloat[2] center
     GLubyte[4] v_color
    ^
 ------------------------------------------------------------
 
 kivent_core/rendering/vertex_formats.pxd:27:4: 'GLubyte' is not a type identifier
 Traceback (most recent call last):
   File "setup.py", line 179, in <module>
     extensions, core_modules)
   File "setup.py", line 159, in build_extensions_for_modules_cython
     return cythonize(ext_list)
   File "/usr/local/lib/python3.5/dist-packages/Cython/Build/Dependencies.py", line 877, in cythonize
     cythonize_one(*args)
   File "/usr/local/lib/python3.5/dist-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
     raise CompileError(None, pyx_file)
 Cython.Compiler.Errors.CompileError: kivent_core/managers/resource_managers.pyx

**Comment by jupart** [comment]
It does compile fine with 1.9.1 though, not an issue since requirement is 1.9.1.

**Comment by Kovak** [comment]
You need the  new_cgl_module branch in order to compile versus master of kivy due to changes in the gl module structure.
