### ISSUE TITLE
[Feature] Add ability to change Entity's animation frames in AnimationComponent

### ISSUE THREAD

**Issue by jupart** [kivy/kivent#193]
Right now, the animation manager loads and stores animations by name, but that information isn't stored in `AnimationComponent`, just a pointer to the frames, which is only set once on `init_component()` in `AnimationSystem`. This hinders `AnimationComponent` by not allowing `Entity`'s to change animations.

I've hacked something together, an `AnimationComponent` property, `data.change_to_frames`, which is checked in `AnimationSystem`'s `update()`. If it's not empty, change `frames*` to the new frames named by `change_to_frames`, set `current_frame_index` to 0, set `current_frame_duration` to 0, and empty `change_to_frames`.

I won't put a PR in yet, I'm having a hard time handling strings in Cython. Right now, I'm storing `change_to_frames` in a char[10] in the `AnimationStruct` (which forces me to use animation names of length 10). If you use a `char*`, the pointer ends up dangling.

**Comment by udiboy1209** [comment]
@jupart why don't you try switching the frames pointer directly instead of passing a string and getting the frames pointer from the manager. I think that would be neater.
And is there some need to use a batching variable to do it in the next frame, and not just switch in the current frame?

The char* breaks because for memory management, each component struct has to be of fixed size. You can have variable length strings in there.

**Comment by jupart** [comment]
I'd definitely like to change `frames*` directly, but components don't have access to managers, right? That's why `frames*` is set in `init_component()` in the system, which does have access to the `gameworld` and thus the managers.

**Comment by udiboy1209** [comment]
Why would you want to make the switch in the component. You can easily do it the system's update function. iirc the system has access to the manager, and even if it doesn't, it won't hurt if it does. I don't fully understand your solution but I do understand your problem. I will come up with a good approach to it.

**Comment by jupart** [comment]
Just to be clear, here's my application. An entity needs to be able to
change animations based on actions, say 'idle', 'jump', 'move', 'shoot',
etc. (frame names in the animation_manager) and I think the best place to
store that data is in the entity's AnimationComponent.

--

Justin Partain
