### ISSUE TITLE
Kivent-Maps: Example 13 runs, but produces console error

### ISSUE THREAD

**Issue by jeffersonheard** [kivy/kivent#197]
`[ERROR  ] OpenGL Error (Renderer._set_blend_func-preglBlendFunc) 1282 / 502 for None`

The example itself just animates random changes of colored tiles, which may well be what it's supposed to do, but I thought I'd mention in case it was supposed to look like something specific.

I just installed kivy from pip and then checked out and built the core and maps modules with kivent. Here is the result of a pip freeze

```
cymunk==0.0.0
Cython==0.24.1
KivEnt-Core==2.2.0.dev0
KivEnt-maps==1.0.0
Kivy==1.9.1
Kivy-Garden==0.1.4
pathlib==1.0.1
requests==2.12.5
six==1.10.0
tmx==1.9.1
```

Platform: OS X 10.11.6
Python: 2.7.11 (system python build)

**Comment by udiboy1209** [comment]
Same as #183. The error has been fixed in new_cgl_module branch

**Comment by Kovak** [comment]
The error is actually in kivy and fixed in 1.9.2 (but you will need new_cgl_module to build against kivy master)

**Comment by spinningD20** [comment]
I'm a code versioning noob, but udiboy1209 has been merging his recent tilemap commits into 2.2dev.  Does that have the new cgl module bit as well?

**Comment by clevermindgames** [comment]
I am getting "[ERROR  ] OpenGL Error (Renderer._set_blend_func-preglBlendFunc) 1282 / 502 for
None" errors in console every frame when I add_widget (pure kivy way) on top of the animated kivent entities, covering them up. When widget is moved away, the error dissapears. Is there a way to silent the errors or avoid getting them in that scenario? Sorry for stupid questions, I am just trying to partly migrate my kivy app to kivent, which I only started learning a couple of days ago.
Awesome framework!
