### ISSUE TITLE
Adding 'normal' kivy elements

### ISSUE THREAD

**Issue by timeyyy** [kivy/kivent#201]
Hi,

I'm using kivy to implement a frontend for the neovim text editor. If the text editor is 80 x 24 (normal terminal size) we have 1920 cells to draw. The biggest performance hit is when scrolling, we need to move most of the cells and then update a few of them a couple of times per second. Full Screen could easily go > 16k cells depending on resolution.

I have looked at the tutorials and played around a little bit but i cannot seem to find any resources on how to add normal kivy `Rectangles` using kivent. How can i do this? Will drawing normal `Rectangles` and `Labels` with kivent provide with me some speed or does most of the magic come with messing around with graphics stuff(shaders/renderer)?

[the cells](https://github.com/nudebandage/KyanVim/blob/master/kyanvim/kv_util.py#L30)

**Comment by timeyyy** [comment]
*Update* ok i have it figured out :grin: will perhaps push an example soon

**Comment by udiboy1209** [comment]
Kivy itself has enough optimisations for the speed you are looking for. Kivent is a game engine and uses a fairly different method of rendering stuff on the screen(entity/component systems model), and while you can add other kivy widgets, kivent wont interfere with them. Why don't you checkout the TextInput class in kivy for what you are making?

**Comment by timeyyy** [comment]
The main reason i cannot use `TextInput` is because the protocol the back end implements doesn't send enough information for me to do handle splits. This limitation will be lifted but i'm not sure when.
