### ISSUE TITLE
can't unload tilemap and load new one

### ISSUE THREAD

**Issue by spinningD20** [kivy/kivent#208]
@udiboy1209  

Spoke to @Kovak on IRC today, and he told me to submit an issue.

see 14_tmx_loader example, modified to try and unload/load a new map.  I'm sure this isn't necessarily the "right" way to try and do this, but I'm more bringing this up because I don't think this scenario was in mind when the tilemap module was written.

Any thoughts?  Relevant code below.  I see a few issues - clearing entities crashes, and if you get past that, you'll probably run into an issue where it tries to load the tileset atlas and it's already been loaded, and then... who knows : )  Good luck!  Let me know what other tests I can provide.

click/touch screen to trigger reloading btw.

https://gist.github.com/spinningD20/5f5b9b45171fe349ebe6ac8180b0a53a

**Comment by spinningD20** [comment]
Any Jedi masters willing to guide this padawan learner?

**Comment by udiboy1209** [comment]
hey @spinningD20 ! I just found some time to look at this issue. The problem I see is that `gameworld.systems_to_add` is set to `None` after `delete_systems` is called probably, so it crashes [here](https://github.com/kivy/kivent/blob/2.2-dev/modules/core/kivent_core/gameworld.pyx#L599). Can you share your error log so I can compare with mine?

**Comment by spinningD20** [comment]
I get the following with the following scenarios so far:

```
    **def screen_touched(self, event):
        self.gameworld.state = 'loading'
        for layer in self.map_layers:
            self.gameworld.delete_system(layer)
        # self.gameworld.clear_entities()
        self.setup_tile_map()**

   _File "/home/mike/kivent/examples/14_tmx_loader/yourappname.kv", line 6, in <module>
     on_touch_down: self.screen_touched(args[1])
   File "/home/mike/kivent/examples/14_tmx_loader/main.py", line 95, in screen_touched
     self.setup_tile_map()
   File "/home/mike/kivent/examples/14_tmx_loader/main.py", line 73, in setup_tile_map
     self.gameworld.init_entity)
   File "/home/mike/pydev/lib/python2.7/site-packages/kivent_maps/map_utils.py", line 124, in init_entities_from_map
     init_entity(comp_data, systems)
   File "kivent_core/gameworld.pyx", line 433, in kivent_core.gameworld.GameWorld.init_entity (kivent_core/gameworld.c:8060)
   File "kivent_core/managers/system_manager.pyx", line 163, in kivent_core.managers.system_manager.SystemManager.__getitem__ (kivent_core/managers/system_manager.c:2137)
 IndexError: list index out of range
 Exception TypeError: "'NoneType' object is not iterable" in 'kivent_core.rendering.batching.IndexedBatch.clear_frames' ignored
 Exception TypeError: "'NoneType' object is not iterable" in 'kivent_core.rendering.batching.IndexedBatch.clear_frames' ignored
 Exception TypeError: "'NoneType' object is not iterable" in 'kivent_core.rendering.batching.IndexedBatch.clear_frames' ignored_


    **def screen_touched(self, event):
        self.gameworld.state = 'loading'
        #for layer in self.map_layers:
        #    self.gameworld.delete_system(layer)
        self.gameworld.clear_entities()
        self.setup_tile_map()**

   _File "/home/mike/kivent/examples/14_tmx_loader/yourappname.kv", line 6, in <module>
     on_touch_down: self.screen_touched(args[1])
   File "/home/mike/kivent/examples/14_tmx_loader/main.py", line 94, in screen_touched
     self.gameworld.clear_entities()
   File "kivent_core/gameworld.pyx", line 546, in kivent_core.gameworld.GameWorld.clear_entities (kivent_core/gameworld.c:10175)
   File "kivent_core/gameworld.pyx", line 487, in kivent_core.gameworld.GameWorld.remove_entity (kivent_core/gameworld.c:8812)
   File "kivent_core/systems/renderers.pyx", line 611, in kivent_core.systems.renderers.Renderer.remove_component (kivent_core/systems/renderers.c:12361)
   File "kivent_core/managers/resource_managers.pyx", line 124, in kivent_core.managers.resource_managers.ModelManager.unregister_entity_with_model (kivent_core/managers/resource_managers.c:5985)
 KeyError: 'tile_472'_

    **def screen_touched(self, event):
        self.gameworld.state = 'loading'
        #for layer in self.map_layers:
        #    self.gameworld.delete_system(layer)
        # self.gameworld.clear_entities()
        self.setup_tile_map()**

_[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):

   File "/home/mike/kivent/examples/14_tmx_loader/main.py", line 115, in <module>
     YourAppNameApp().run()
   File "/home/mike/pydev/lib/python2.7/site-packages/kivy/app.py", line 828, in run
     runTouchApp()
   File "/home/mike/pydev/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)_
```

**Comment by spinningD20** [comment]
Also, I think @Kovak mentioned that deleting and adding systems would possibly lead to fragmented memory.  I'd love to be able to re-use the map renderers and animator systems, and have the number of them be a property I can set, that perhaps the map manager can handle allocating (instead of just on initialization).

**Comment by udiboy1209** [comment]
You can certainly initialize any number of systems for an arbitrary number of layers. Currently the maps module requires you to specify the number [like here](https://github.com/kivy/kivent/blob/master/examples/14_tmx_loader/main.py#L43). In that tmx loader example we have specified 4 layers. You can very simply specify more layers than necessary without any major problem expect for consuming resources.

So if you have 3 maps with 4, 6 and 3 layers each, then you can initialize the gameworld with 6 sets of map layer systems, and then load/remove the map entities in any order(even multiple together) without problems. This works because the `init_entities_from_map`  function will use a standard format of system names by layer, which is what `load_map_systems` creates. As long as there are enough number of systems (layers) initialized, you shouldn't have problems loading any map. 

If switching between maps is all you require then this method should work. I will have to see further why removing systems isn't working. Also, do suggest if a module level function would be better for removing a map/switching maps.

**Comment by Kovak** [comment]
Just wanted to note, you definitely should not try to delete a system
before clearing all the entities that may have components of that system.

**Comment by spinningD20** [comment]
Good to know, but yeah, gameworld.clear_entities() tries to find a matching model to unregister (as noted above) and dies there.  

Otherwise, based on what Kovak is saying, delete_system is not going to work without first clearing the entities.  Is this KeyError noted above when trying to call clear_entities happening for you guys as well?

**Comment by spinningD20** [comment]
I'm at least functioning for now with my branch and will move on with my game development, but this feature will probably need fleshed out more, especially for considering multiple tilesets, maps, and handling loading images/textures.  

I cleaned up my current branch a little more, in case anyone is interested in how I worked around some issues.

https://github.com/spinningD20/kivent/tree/current
