### ISSUE TITLE
Why kivent_core does not work on android OS?

### ISSUE THREAD

**Issue by IvanDragogear** [kivy/kivent#212]
I am dedicated to the development of games in my free time,because pygame does not handle multitouch I'm using kivy, but when I want to include kivent_core for better performance,my games stop working on android. This is what the terminal displays when debugging:

```
I/python  (28331): [INFO   ] [GL          ] OpenGL parsed version: 2, 0
I/python  (28331): [INFO   ] [GL          ] Texture max size <4096>
I/python  (28331): [INFO   ] [GL          ] Texture max units <8>
I/python  (28331): [INFO   ] [Window      ] auto add sdl2 input provider
I/python  (28331): [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
I/python  (28331):  Traceback (most recent call last):
I/python  (28331):    File "/home/ivandg/Practica_1/main.py", line 4, in <module>
I/python  (28331):    File "/home/ivandg/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivent_core/__init__.py", line 8, in <module>
I/python  (28331):    File "/home/ivandg/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivent_core/rendering/__init__.py", line 3, in <module>
I/python  (28331):    File "kivent_core/systems/gamesystem.pxd", line 3, in init kivent_core.rendering.cmesh (kivent_core/rendering/cmesh.c:3798)
I/python  (28331):    File "/home/ivandg/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivent_core/systems/__init__.py", line 1, in <module>
I/python  (28331):    File "kivent_core/managers/game_manager.pxd", line 3, in init kivent_core.systems.gamesystem (kivent_core/systems/gamesystem.c:4792)
I/python  (28331):    File "/home/ivandg/.local/share/python-for-android/dists/unnamed_dist_1/private/lib/python2.7/site-packages/kivent_core/managers/__init__.py", line 1, in <module>
I/python  (28331):    File "vertex_instructions.pxd", line 21, in init kivent_core.managers.resource_managers (kivent_core/managers/resource_managers.c:26770)
I/python  (28331):  ValueError: kivy.graphics.vertex_instructions.Mesh has the wrong size, try recompiling
I/python  (28331): Python for android ended.
```

I use python-for-android to create the APK.

**Comment by Kovak** [comment]
this error means that the KivEnt was compiled against a different Kivy then the Kivy that was compiled for the device

how did you include kivent in your package?

**Comment by IvanDragogear** [comment]
I use p4a to include kivent core: 
`p4a apk --private /home/ivandg/Practica_1 --package=org.example.myapp --name "Practica_1" --version 0.05 --bootstrap=sdl2 --orientation=landscape --requirements=python2,kivy,kivent_core,kivent_cymunk
`
My kivy version: 1.9.1 (Pc)
My kivent version: 2.2 (Pc)

**Comment by IvanDragogear** [comment]
Thank you Kovak.
I already found the solution, this is what i did:

Uninstall kivy 1.9.1
Uninstall python-kivy
Install kivy-master (1.9.2) Download from here: [kivy-master](https://github.com/kivy/kivy)
Install kivent-new_cgl_module (2.2) Download from here:  [kivent-new_cgl_modul](https://github.com/kivy/kivent/tree/new_cgl_module)
Create apk with buildozer: `buildozer -v android debug`
If buildozer fails, change the recipes for kiven_core and kivent_cymunk that are in the folder YourApp/.buildozer/android/platform/python-for-android/recipes for the recipes that are in kivent-new_cgl_module/modules/recipes

I found this on google forums in which you participated Kovak, thank you.
Here I only put it in steps for newbies like me.

**Comment by Kovak** [comment]
awesome thanks for sharing the solution :)
