### ISSUE TITLE
Problem with the rendering order of entities.

### ISSUE THREAD

**Issue by IvanDragogear** [kivy/kivent#213]
Hello, I'm creating a game based on isometric tilemap, the game creates cubes of different sizes that are then covered with a texture (entities), the last cube to be rendered is orange, but for some reason render it behind the multicolored wall.

The order in which the objects are initiated:
1.-White and gray floor (12x12 entities)
2.- Red wall  (12x6 entities)
3.- Multicolored wall (12x6 entities)
4.- Orange cube (3x3x3 entities)
In this scene 315 entities are rendered

Why does the orange cube appear behind if its entities are the last to begin?
Is there any way to control the order in which entities are rendered?

![01](https://cloud.githubusercontent.com/assets/26156036/24069287/a1462842-0b69-11e7-95f1-5ad572b1873d.png)
![02](https://cloud.githubusercontent.com/assets/26156036/24069289/af39d8cc-0b69-11e7-96ed-956e8ffeffc5.png)

**Comment by udiboy1209** [comment]
Move the cube to a layer which is on top of the wall layers. You can check how to make multiple layers in the example.

**Comment by IvanDragogear** [comment]
I am not using python-tmx, I need to be able to identify all the cubes,to interact with them in very different ways, that's why i do not use tmx.

**Comment by udiboy1209** [comment]
@IvanDragogear you need not use tmx. When creating the tiles list, each map location will have a list of tiles. For the locations with the cube, make that list have one element with layer=1 in the dict.

You will also need to initialize multiple layer systems. Show me your code and I'll point out where to make changes.

**Comment by IvanDragogear** [comment]
Sorry, I'm still new using git, Here is my code: [https://github.com/IvanDragogear/Kiv_Tile_Isometricos](url)
This is the file that initializes the entities: [https://github.com/IvanDragogear/Kiv_Tile_Isometricos/blob/master/Maquinaria/Constructor/Vista_Isometrica.py](url)

Thanks for helping me.
