### ISSUE TITLE
CymunkPhysics does not allow clear entities

### ISSUE THREAD

**Issue by IvanDragogear** [kivy/kivent#252]
Hello, I have a very advanced game made with kivent, the problem is that this has mini games and to change from one to another I need to delete previously created entities. This is what i'm doing now, but obviously not working:
```
def setup_states(self):
		self.gameworld.add_state(
		state_name ='main',
		systems_added =['renderer'],
		systems_removed = [],
		systems_paused = [],
		systems_unpaused = ['cymunk_physics','camara01','player','enemy'],
		screenmanager_screen = 'main')
		
		self.gameworld.add_state(
		state_name ='pause',
		systems_added =[],
		systems_removed = [],
		systems_paused = ['cymunk_physics','camara01','player','enemy'],
		systems_unpaused = [])

def state_pause(self):
		self.gameworld.state = 'pause'
                self.gameworld.clear_entities()
```
When I run state_paused() this is what the console shows me:

Aborting due to Chipmunk error: This operation cannot be done safely during a call to cpSpaceStep() or during a query. Put these calls into a post-step callback.
	Failed condition: !space->locked
	Source:/tmp/pip-UVvYGn-build/cymunk/Chipmunk-Physics/src/cpSpace.c:378
Aborted (core dumped)

**Comment by Kovak** [comment]
This only occurs if you try to remove an entity during the processing of the physics space step. This typically only happens if you remove an entity as part of a collision callback.  Are you causing your state_pause change as part of a physics callback?

The solution is either to use Gameworld.timed_remove_entity to remove entities with logic in a callback or to make sure the clear runs outside of the physics step.

**Comment by IvanDragogear** [comment]
Thanks for the guide, I already managed to solve it:
```
def setup_states(self):
		self.gameworld.add_state(
		state_name ='main',
		systems_added =['renderer'],
		systems_removed = [],
		systems_paused = [],
		systems_unpaused = ['cymunk_physics','camara01','player','enemy'],
		screenmanager_screen = 'main')
		
		self.gameworld.add_state(
		state_name ='pause',
		systems_added =[],
		systems_removed = [],
		systems_paused = ['cymunk_physics','camara01','player','enemy'],
		systems_unpaused = [],
                on_change_callback=self.clear_entities) #←←←←change here

def state_pause(self):
		self.gameworld.state = 'pause'
                                                                                 #←←←←change here
def clear_entities(self):                                             #←←←←change here
                self.gameworld.clear_entities()                #←←←←change here
```
In this way I only call the function state_pause() and everything ok.
