### ISSUE TITLE
Cannot install kivent_core on Windows 10 64bit python27

### ISSUE THREAD

**Issue by acote5** [kivy/kivent#269]
I installed python 2.7 from scratch, installed the most recent Kivy development version (successfully). Then, when I go to compile kivent_core, I get several warnings with the following issue "warning: unknown conversion type character 'z' in format".

It seems to be some settings issues related to mingw32. Anyone figured out a workaround/fix?

**Comment by Kovak** [comment]
these warnings are not a big deal and should not have stopped the compilation from happening, your install should be fine unless there is something more critical that also went wrong.

**Comment by acote5** [comment]
Ok. Thanks for the info. It was indeed compiling. I got one of the examples to run properly. Thanks!
