### ISSUE TITLE
Kivent does not work only with python

### ISSUE THREAD

**Issue by alperbulbul1** [kivy/kivent#279]
I try .kv file with kivent tutorial examples/0_empty_kivy_app and i have gameworld has no attribut e issue i used kivy 2.0.0.dev  python 3.6.8 than i try only python scripts. My code is  

from kivy.app import App
from kivy.uix.widget import Widget
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.label import Label
from kivy.clock import Clock
from kivy.core.window import Window
from kivy.properties import StringProperty, ObjectProperty
import kivent_core
from kivent_core.gameworld import GameWorld
from kivent_core.uix.gamescreens import GameScreenManager, GameScreen
from kivent_core.systems.renderers import RotateColorScaleRenderer
from kivent_core.systems.position_systems import PositionSystem2D
from kivent_core.systems.scale_systems import ScaleSystem2D
from kivent_core.systems.color_systems import ColorSystem
from kivent_core.systems.rotate_systems import RotateSystem2D

class TestGame(Widget):
    def __init__(self, **kwargs):
        super(TestGame, self).__init__(**kwargs)
        self.gameworld.init_gameworld(
        ["renderer", "position", "rotate", "color", "scale"], callback=self.init_game
        )

    gamescreenmanager = ObjectProperty(None)
    position = ObjectProperty(None)
    scale = ObjectProperty(None)
    color = ObjectProperty(None)
    rotate = ObjectProperty(None)
    renderer = ObjectProperty(None)
    gameworld = ObjectProperty(None)
    
    def on_start(self):
        self.gamescreenmanager = GameScreenManager()
        self.gamescreenmanager.add_widget(MainScreen(name="main"))
        self.add_widget(self.gamescreenmanager)
        self.position = PositionSystem2D(
            system_id='position',
            zones=['general'])
        self.scale = ScaleSystem2D(
            system_id="scale",
            zones=["general"])
        self.color = ColorSystem(
            system_id="color",
            zones=["general"])
        self.rotate = RotateSystem2D(
            system_id="rotate",
            zones=["general"])
        self.renderer = RotateColorScaleRenderer(
            system_id="renderer",
            zones=["general"],
            shader_source='assets/glsl/positionshader.glsl',
            system_names=["renderer", "position", "rotate", "color", "scale"])
        self.gameworld = GameWorld(
            gamescreenmanager=self.gamescreenmanager,
            size_of_gameworld=100 * 1024,
            system_count=5,
            zones={'general': 10000},
            system_manager=(self.position, self.scale, self.color, self.rotate, self.renderer))
    def init_game(self):
        self.setup_states()
        self.set_state()

    def setup_states(self):
        self.gameworld.add_state(state_name="main",
        system_added=["renderer", "position", "rotate", "color", "scale"],
        system_removed=[], system_paused=[],
        system_unpaused=["renderer", "position", "rotate", "color", "scale"],
        screenmanager_screen="main")

    def set_state(self):
        self.gameworld.state = "main"

class MainScreen(GameScreen):
    def __init__(self, **kwargs):
        super(MainScreen, self).__init__(**kwargs)
        self.lyt = FloatLayout()
        self.lab = DebugPanel()
        self.lyt.add_widget(self.lab)
        self.add_widget(self.lyt)

class DebugPanel(Widget):
    fps = StringProperty(None)
    def __init__(self, **kwargs):
        super(DebugPanel, self).__init__(**kwargs)
        Clock.schedule_once(self.update_fps)
        self.text = StringProperty(None)
        if self.fps is not None:
            self.text = "FPS: " + self.fps
        else:
            self.text = "FPS:"
        self.lab = Label(halign='center',
        valign='middle',
        color=(1,1,1,1),
        text=self.text)

    def update_fps(self,dt):
        self.fps = str(int(Clock.get_fps()))
        Clock.schedule_once(self.update_fps, .05)

class TryApp(App):
    def build(self):
        Window.clearcolor = (0, 0, 0 ,1)
        return TestGame()

if __name__ == "__main__":
    TryApp().run()

Empty screen showed up and terminal result is:

[INFO   ] [Logger      ] Record log in /home/alper/.kivy/logs/kivy_19-09-23_82.txt
[INFO   ] [Kivy        ] v2.0.0.dev0, git-0d1156a, 20190922
[INFO   ] [Kivy        ] Installed at "/home/alper/kivy/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/home/alper/Game/bin/python"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 19.0.8'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Haswell Mobile '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: kivy._event.EventDispatcher size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
   return f(*args, **kwds)
 /usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: kivy.graphics.context_instructions.Scale size changed, may indicate binary incompatibility. Expected 136 from C header, got 144 from PyObject
   return f(*args, **kwds)
[INFO   ] [AudioGstplayer] Using Gstreamer 1.14.5.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)
 Traceback (most recent call last):
   File "/home/alper/Game/Try.py", line 112, in <module>
     TryApp().run()
   File "/home/alper/kivy/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/alper/kivy/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "/home/alper/Game/Try.py", line 108, in build
     return TestGame()
   File "/home/alper/Game/Try.py", line 21, in __init__
     self.gameworld.init_gameworld(
 AttributeError: 'NoneType' object has no attribute 'init_gameworld'

Process finished with exit code 1

**Comment by thegameguy** [comment]
@alperbulbul1, 
you have declared: gameworld = ObjectProperty(None) 
that is why your getting: AttributeError: 'NoneType' object has no attribute 'init_gameworld'
I suggest that you use kv.file the way its been suggested. For more examples on Kivent you can visit
https://github.com/thegameguy/Kivent-Game-Engine---Tutorials
and if you want video assistance you can visit: 
https://www.youtube.com/watch?v=IRLGiRdmq90&list=PLMcvKw_Cz2u9OtgMs2roqDskXhK9YHVDJ

**Comment by alperbulbul1** [comment]
Thank you very much. İt seems TestGame: declaration is make problem. When İ remove it problem is solve
