### ISSUE TITLE
Cython error while compiling core for KivEnt 3.0

### ISSUE THREAD

**Issue by BlizzardBlack** [kivy/kivent#283]
I tried to install the new KivEnt 3.0 on Ubuntu 18.03 and got the following error, which did not happen when I was installing KivEnt 2.2:
```
[INFO   ] Logger: Record log in /home/admin/.kivy/logs/kivy_19-10-19_1.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/home/admin/.local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.7.4 (default, Sep 16 2019, 01:30:27) 
[GCC 7.4.0]
[INFO   ] Python: Interpreter at "/usr/local/bin/python3.7"
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr: cdef class VertexInstruction
[WARNING] stderr: cdef class CanvasBase
[WARNING] stderr: cdef class Canvas
[WARNING] stderr: cdef class RenderContext
[WARNING] stderr: 
[WARNING] stderr: from vbo cimport *
[WARNING] stderr: ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:11:0: 'vbo.pxd' not found
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr: cdef class CanvasBase
[WARNING] stderr: cdef class Canvas
[WARNING] stderr: cdef class RenderContext
[WARNING] stderr: 
[WARNING] stderr: from vbo cimport *
[WARNING] stderr: from compiler cimport *
[WARNING] stderr: ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:12:0: 'compiler.pxd' not found
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr: cdef class Canvas
[WARNING] stderr: cdef class RenderContext
[WARNING] stderr: 
[WARNING] stderr: from vbo cimport *
[WARNING] stderr: from compiler cimport *
[WARNING] stderr: from shader cimport *
[WARNING] stderr: ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:13:0: 'shader.pxd' not found
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr: cdef class RenderContext
[WARNING] stderr: 
[WARNING] stderr: from vbo cimport *
[WARNING] stderr: from compiler cimport *
[WARNING] stderr: from shader cimport *
[WARNING] stderr: from texture cimport Texture
[WARNING] stderr: ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:14:0: 'texture.pxd' not found
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr: cdef class RenderContext
[WARNING] stderr: 
[WARNING] stderr: from vbo cimport *
[WARNING] stderr: from compiler cimport *
[WARNING] stderr: from shader cimport *
[WARNING] stderr: from texture cimport Texture
[WARNING] stderr: ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:14:0: 'texture/Texture.pxd' not found
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr:     cdef void rremove(self, InstructionGroup ig)
[WARNING] stderr: 
[WARNING] stderr: cdef class InstructionGroup(Instruction):
[WARNING] stderr:     cdef public list children
[WARNING] stderr:     cdef InstructionGroup compiled_children
[WARNING] stderr:     cdef GraphicsCompiler compiler
[WARNING] stderr:         ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:45:9: 'GraphicsCompiler' is not a type identifier
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr:     cdef int set_state(self, str name, value) except -1
[WARNING] stderr:     cdef int push_state(self, str name) except -1
[WARNING] stderr:     cdef int pop_state(self, str name) except -1
[WARNING] stderr: 
[WARNING] stderr: 
[WARNING] stderr: from context_instructions cimport BindTexture
[WARNING] stderr: ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:66:0: 'context_instructions.pxd' not found
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr:     cdef int set_state(self, str name, value) except -1
[WARNING] stderr:     cdef int push_state(self, str name) except -1
[WARNING] stderr:     cdef int pop_state(self, str name) except -1
[WARNING] stderr: 
[WARNING] stderr: 
[WARNING] stderr: from context_instructions cimport BindTexture
[WARNING] stderr: ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:66:0: 'context_instructions/BindTexture.pxd' not found
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr: 
[WARNING] stderr: 
[WARNING] stderr: from context_instructions cimport BindTexture
[WARNING] stderr: 
[WARNING] stderr: cdef class VertexInstruction(Instruction):
[WARNING] stderr:     cdef BindTexture texture_binding
[WARNING] stderr:         ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:69:9: 'BindTexture' is not a type identifier
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr: 
[WARNING] stderr: from context_instructions cimport BindTexture
[WARNING] stderr: 
[WARNING] stderr: cdef class VertexInstruction(Instruction):
[WARNING] stderr:     cdef BindTexture texture_binding
[WARNING] stderr:     cdef VertexBatch batch
[WARNING] stderr:         ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:70:9: 'VertexBatch' is not a type identifier
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr:     cdef void rremove(self, InstructionGroup ig)
[WARNING] stderr: 
[WARNING] stderr:     cdef void build(self)
[WARNING] stderr: 
[WARNING] stderr: cdef class Callback(Instruction):
[WARNING] stderr:     cdef Shader _shader
[WARNING] stderr:         ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:80:9: 'Shader' is not a type identifier
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr:     cpdef draw(self)
[WARNING] stderr:     cdef int apply(self) except -1
[WARNING] stderr: 
[WARNING] stderr: 
[WARNING] stderr: cdef class RenderContext(Canvas):
[WARNING] stderr:     cdef Shader _shader
[WARNING] stderr:         ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:106:9: 'Shader' is not a type identifier
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr: 
[WARNING] stderr: 
[WARNING] stderr: cdef class RenderContext(Canvas):
[WARNING] stderr:     cdef Shader _shader
[WARNING] stderr:     cdef dict state_stacks
[WARNING] stderr:     cdef Texture default_texture
[WARNING] stderr:         ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:108:9: 'Texture' is not a type identifier
[WARNING] stderr: 
[WARNING] stderr: Error compiling Cython file:
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: ...
[WARNING] stderr:     cdef dict bind_texture
[WARNING] stderr:     cdef int _use_parent_projection
[WARNING] stderr:     cdef int _use_parent_modelview
[WARNING] stderr:     cdef int _use_parent_frag_modelview
[WARNING] stderr: 
[WARNING] stderr:     cdef void set_texture(self, int index, Texture texture)
[WARNING] stderr:                                           ^
[WARNING] stderr: ------------------------------------------------------------
[WARNING] stderr: 
[WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:114:43: 'Texture' is not a type identifier
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "setup.py", line 184, in <module>
[WARNING] stderr:     extensions, core_modules)
[WARNING] stderr:   File "setup.py", line 164, in build_extensions_for_modules_cython
[WARNING] stderr:     return cythonize(ext_list, compiler_directives={'language_level': '3'})
[WARNING] stderr:   File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
[WARNING] stderr:     cythonize_one(*args)
[WARNING] stderr:   File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
[WARNING] stderr:     raise CompileError(None, pyx_file)
[WARNING] stderr: Cython.Compiler.Errors.CompileError: kivent_core/managers/resource_managers.pyx
```
I checked the `python3.7/site-packages/kivy/graphics/` directory and confirmed those .pxd files reported not found actually exist in the directory.
Cython version is 0.29.13. Any help is greatly appreciated.

**Comment by yobagram** [comment]
> I tried to install the new KivEnt 3.0 on Ubuntu 18.03 and got the following error, which did not happen when I was installing KivEnt 2.2:
> 
> ```
> [INFO   ] Logger: Record log in /home/admin/.kivy/logs/kivy_19-10-19_1.txt
> [INFO   ] Kivy: v1.11.1
> [INFO   ] Kivy: Installed at "/home/admin/.local/lib/python3.7/site-packages/kivy/__init__.py"
> [INFO   ] Python: v3.7.4 (default, Sep 16 2019, 01:30:27) 
> [GCC 7.4.0]
> [INFO   ] Python: Interpreter at "/usr/local/bin/python3.7"
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr: cdef class VertexInstruction
> [WARNING] stderr: cdef class CanvasBase
> [WARNING] stderr: cdef class Canvas
> [WARNING] stderr: cdef class RenderContext
> [WARNING] stderr: 
> [WARNING] stderr: from vbo cimport *
> [WARNING] stderr: ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:11:0: 'vbo.pxd' not found
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr: cdef class CanvasBase
> [WARNING] stderr: cdef class Canvas
> [WARNING] stderr: cdef class RenderContext
> [WARNING] stderr: 
> [WARNING] stderr: from vbo cimport *
> [WARNING] stderr: from compiler cimport *
> [WARNING] stderr: ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:12:0: 'compiler.pxd' not found
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr: cdef class Canvas
> [WARNING] stderr: cdef class RenderContext
> [WARNING] stderr: 
> [WARNING] stderr: from vbo cimport *
> [WARNING] stderr: from compiler cimport *
> [WARNING] stderr: from shader cimport *
> [WARNING] stderr: ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:13:0: 'shader.pxd' not found
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr: cdef class RenderContext
> [WARNING] stderr: 
> [WARNING] stderr: from vbo cimport *
> [WARNING] stderr: from compiler cimport *
> [WARNING] stderr: from shader cimport *
> [WARNING] stderr: from texture cimport Texture
> [WARNING] stderr: ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:14:0: 'texture.pxd' not found
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr: cdef class RenderContext
> [WARNING] stderr: 
> [WARNING] stderr: from vbo cimport *
> [WARNING] stderr: from compiler cimport *
> [WARNING] stderr: from shader cimport *
> [WARNING] stderr: from texture cimport Texture
> [WARNING] stderr: ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:14:0: 'texture/Texture.pxd' not found
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr:     cdef void rremove(self, InstructionGroup ig)
> [WARNING] stderr: 
> [WARNING] stderr: cdef class InstructionGroup(Instruction):
> [WARNING] stderr:     cdef public list children
> [WARNING] stderr:     cdef InstructionGroup compiled_children
> [WARNING] stderr:     cdef GraphicsCompiler compiler
> [WARNING] stderr:         ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:45:9: 'GraphicsCompiler' is not a type identifier
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr:     cdef int set_state(self, str name, value) except -1
> [WARNING] stderr:     cdef int push_state(self, str name) except -1
> [WARNING] stderr:     cdef int pop_state(self, str name) except -1
> [WARNING] stderr: 
> [WARNING] stderr: 
> [WARNING] stderr: from context_instructions cimport BindTexture
> [WARNING] stderr: ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:66:0: 'context_instructions.pxd' not found
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr:     cdef int set_state(self, str name, value) except -1
> [WARNING] stderr:     cdef int push_state(self, str name) except -1
> [WARNING] stderr:     cdef int pop_state(self, str name) except -1
> [WARNING] stderr: 
> [WARNING] stderr: 
> [WARNING] stderr: from context_instructions cimport BindTexture
> [WARNING] stderr: ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:66:0: 'context_instructions/BindTexture.pxd' not found
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr: 
> [WARNING] stderr: 
> [WARNING] stderr: from context_instructions cimport BindTexture
> [WARNING] stderr: 
> [WARNING] stderr: cdef class VertexInstruction(Instruction):
> [WARNING] stderr:     cdef BindTexture texture_binding
> [WARNING] stderr:         ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:69:9: 'BindTexture' is not a type identifier
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr: 
> [WARNING] stderr: from context_instructions cimport BindTexture
> [WARNING] stderr: 
> [WARNING] stderr: cdef class VertexInstruction(Instruction):
> [WARNING] stderr:     cdef BindTexture texture_binding
> [WARNING] stderr:     cdef VertexBatch batch
> [WARNING] stderr:         ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:70:9: 'VertexBatch' is not a type identifier
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr:     cdef void rremove(self, InstructionGroup ig)
> [WARNING] stderr: 
> [WARNING] stderr:     cdef void build(self)
> [WARNING] stderr: 
> [WARNING] stderr: cdef class Callback(Instruction):
> [WARNING] stderr:     cdef Shader _shader
> [WARNING] stderr:         ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:80:9: 'Shader' is not a type identifier
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr:     cpdef draw(self)
> [WARNING] stderr:     cdef int apply(self) except -1
> [WARNING] stderr: 
> [WARNING] stderr: 
> [WARNING] stderr: cdef class RenderContext(Canvas):
> [WARNING] stderr:     cdef Shader _shader
> [WARNING] stderr:         ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:106:9: 'Shader' is not a type identifier
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr: 
> [WARNING] stderr: 
> [WARNING] stderr: cdef class RenderContext(Canvas):
> [WARNING] stderr:     cdef Shader _shader
> [WARNING] stderr:     cdef dict state_stacks
> [WARNING] stderr:     cdef Texture default_texture
> [WARNING] stderr:         ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:108:9: 'Texture' is not a type identifier
> [WARNING] stderr: 
> [WARNING] stderr: Error compiling Cython file:
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: ...
> [WARNING] stderr:     cdef dict bind_texture
> [WARNING] stderr:     cdef int _use_parent_projection
> [WARNING] stderr:     cdef int _use_parent_modelview
> [WARNING] stderr:     cdef int _use_parent_frag_modelview
> [WARNING] stderr: 
> [WARNING] stderr:     cdef void set_texture(self, int index, Texture texture)
> [WARNING] stderr:                                           ^
> [WARNING] stderr: ------------------------------------------------------------
> [WARNING] stderr: 
> [WARNING] stderr: /home/admin/.local/lib/python3.7/site-packages/kivy/graphics/instructions.pxd:114:43: 'Texture' is not a type identifier
> [WARNING] stderr: Traceback (most recent call last):
> [WARNING] stderr:   File "setup.py", line 184, in <module>
> [WARNING] stderr:     extensions, core_modules)
> [WARNING] stderr:   File "setup.py", line 164, in build_extensions_for_modules_cython
> [WARNING] stderr:     return cythonize(ext_list, compiler_directives={'language_level': '3'})
> [WARNING] stderr:   File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
> [WARNING] stderr:     cythonize_one(*args)
> [WARNING] stderr:   File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
> [WARNING] stderr:     raise CompileError(None, pyx_file)
> [WARNING] stderr: Cython.Compiler.Errors.CompileError: kivent_core/managers/resource_managers.pyx
> ```
> 
> I checked the `python3.7/site-packages/kivy/graphics/` directory and confirmed those .pxd files reported not found actually exist in the directory.
> Cython version is 0.29.13. Any help is greatly appreciated.

Did you install Kivy from cloned master repository? For using Kivent, you must build Kivy too. See Kivy documentation. By the way, I have some problems with working Kivy in fullscreen( black screen, alt_tab don't work), so I build Kivent for Windows and use it without problems.

**Comment by BlizzardBlack** [comment]
> > I tried to install the new KivEnt 3.0 on Ubuntu 18.03 and got the following error, which did not happen when I was installing KivEnt 2.2:
> 
> > I checked the `python3.7/site-packages/kivy/graphics/` directory and confirmed those .pxd files reported not found actually exist in the directory.
> > Cython version is 0.29.13. Any help is greatly appreciated.
> 
> Did you install Kivy from cloned master repository? For using Kivent, you must build Kivy too. See Kivy documentation. By the way, I have some problems with working Kivy in fullscreen( black screen, alt_tab don't work), so I build Kivent for Windows and use it without problems.

Thank you! I was using the stable build. I tried cloning and building Kivy from the master repository as you suggest, and this resolved the problem. I guess Kivy stable builds are probably not intended for KivEnt.
