### ISSUE TITLE
Unable to run tutorial apps.

### ISSUE THREAD

**Issue by holtalanm** [kivy/kivent#62]
Just pulled down your project.  Was super excited to see that someone was working on a python game engine!

I followed your setup instructions (actually, did it twice after I got the below error the first time), but when I try to run the basic app example, it get the following error:

 Traceback (most recent call last):
   File "main.py", line 6, in <module>
     import kivent_core
   File "/opt/kivent/kivent_tutorials/2_basic_app/kivent_core/__init__.py", line 1, in <module>
     import cmesh
   File "texture.pxd", line 3, in init kivent_core.cmesh (kivent_core/cmesh.c:3271)
 ValueError: kivy.graphics.texture.Texture has the wrong size, try recompiling

I'm not experienced enough with cython to know exactly what went wrong, but would love a little direction on where to go to get this resolved.  Thanks!

**Comment by chozabu** [comment]
I could be way off the mark - but I've had this error when KivEnt is compiled against a different version of kivy than the version I am trying to run it with.  

Do you have another version of kivy installed from a package manager?  

try pulling latest Kivy, compile it - check your pythonpath, compile KivEnt again.
Also, you should probably currently be on the new_rendering branch of KivEnt.

**Comment by Kovak** [comment]
Which version of kivy are you using?

**Comment by holtalanm** [comment]
I had another version of kivy that had been installed via pycharm.  I removed it and rebuilt kivent using the master branch of kivy on github.

Still getting the same error.

**Comment by Kovak** [comment]
This error still means that KivEnt was compiled with a different Kivy from the one it is trying to be used in.
