### ISSUE TITLE
Examples 2-7 only work when executed from their own directory

### ISSUE THREAD

**Issue by craighay1** [kivy/kivent#69]
Examples 2-7 give the error:
IOError: [Errno 2] No such file or directory: '../assets/background_objects.atlas'
when you try to run them from outside their own directory.

The relative paths should be changed to use:
os.path.join(os.path.dirname(__file__), '..', 'assets', 'background_objects.atlas')
to solve this issue.

**Comment by Kovak** [comment]
Sorry it's been over a week since you reported this, I meant to fix but haven't had a chance yet. Thank you for reporting, I'll try to address soon.

**Comment by Kovak** [comment]
Fixed in new_model_format, will be released this weekend as KivEnt 2.1
