### ISSUE TITLE
rebatching issue

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/kivent#70]
There is problem, when texture key is changed and new texture is on the different sheet of atlas than previous. 

See testcase:  https://bitbucket.org/maho/tmpkh2/ , when you run python khamster.py
- every time frame is changing from that with "1" drawn on it, to that
with "2" drawn on it, it flickers, and I see following error on console:

Exception ValueError: 'list.remove(x): x not in list' in
'kivent_core.rendering.batching.BatchManager.remove_batch' ignored

Changing texture and rebatching is here:
https://bitbucket.org/maho/tmpkh2/src/6b1431740af1e4befe27866604deab808472f13e/anim.py?at=default#cl-123

**Comment by Kovak** [comment]
You're probably is that you are unbatching the entity after changing its texture.

You must unbatch the entity and then change the texture and then rebatch the entity.

In the next release this will be handled automatically for you.

**Comment by mahomahomaho** [comment]
W dniu 05.06.2015 o 20:16, Kovak pisze:
> You're probably is that you are unbatching the entity after changing its
> texture.
> 
> You must unbatch the entity and then change the texture and then rebatch
> the entity.

I did as you suggested (and commited into hg repo) and effect is exactly
the same.
> 
> In the next release this will be handled automatically for you.

Oh, it would be great.

**Comment by Kovak** [comment]
If you committed it into the same as you linked before, you have not done as I suggested:

```python
def on_texture_changed(self,texture):
        tw,th = texture_manager.get_size_by_name(texture)
        entity = self.entity()
        entity.rotate_renderer.texture_key=texture
        self.renderer.unbatch_entity(self.current_entity)
        self.renderer.batch_entity(self.current_entity)
        if tw!=entity.rotate_renderer.width or th!=entity.rotate_renderer.height or self.phase_changed:
            self.phase_changed = False
            self.replace_entity(tw, th)
```

should be

```python
def on_texture_changed(self,texture):
        tw,th = texture_manager.get_size_by_name(texture)
        entity = self.entity()
 self.renderer.unbatch_entity(self.current_entity)
        entity.rotate_renderer.texture_key=texture
       
        self.renderer.batch_entity(self.current_entity)
        if tw!=entity.rotate_renderer.width or th!=entity.rotate_renderer.height or self.phase_changed:
            self.phase_changed = False
            self.replace_entity(tw, th)

**Comment by mahomahomaho** [comment]
W dniu 05.06.2015 o 22:35, Kovak pisze:
> If you committed it into the same as you linked before, you have not
> done as I suggested:
> 
> def on_texture_changed(self,texture):
>         tw,th = texture_manager.get_size_by_name(texture)
>         entity = self.entity()
>         entity.rotate_renderer.texture_key=texture
>         self.renderer.unbatch_entity(self.current_entity)
>         self.renderer.batch_entity(self.current_entity)
>         if tw!=entity.rotate_renderer.width or th!=entity.rotate_renderer.height or self.phase_changed:
>             self.phase_changed = False
>             self.replace_entity(tw, th)
> 
> should be
> 
> def on_texture_changed(self,texture):
>         tw,th = texture_manager.get_size_by_name(texture)
>         entity = self.entity()
>  self.renderer.unbatch_entity(self.current_entity)
>         entity.rotate_renderer.texture_key=texture
> 
>         self.renderer.batch_entity(self.current_entity)
>         if tw!=entity.rotate_renderer.width or th!=entity.rotate_renderer.height or self.phase_changed:
>             self.phase_changed = False
>             self.replace_entity(tw, th)

See
https://bitbucket.org/maho/tmpkh2/commits/53fa71fed66e002e4be2a9ef56aa2ac297aeb61d
- you probably forgot to pull.

Note, that it not always flickers, but usually. Error in output shows
always.

**Comment by Kovak** [comment]
@mahomahomaho  I haven't had time to completely finish investigating, but my latest work does not display the issues you are experiencing.

You can see how rebatching is accomplished automatically here: 
https://github.com/kivy/kivent/blob/new_model_format/modules/core/kivent_core/systems/renderers.pyx#L138

and an example of animating entities:

https://github.com/kivy/kivent/tree/new_model_format/examples/8_test_batching

I will have to look into why it is not working on the master branch when I have some more time, but maybe the code in new_model_format can help you figure out what is going on.

**Comment by mahomahomaho** [comment]
W dniu 06.06.2015 o 20:14, Kovak pisze:
> @mahomahomaho <https://github.com/mahomahomaho> I haven't had time to
> completely finish investigating, but my latest work does not display the
> issues you are experiencing.

Funny thing - I no longer see flickering, while I still have error in
console ("Exception ValueError: 'list.remove(x): x not in list' in
'kivent_core.rendering.batching.BatchManager.remove_batch' ignored")

**Comment by mahomahomaho** [comment]
I tried to use that branch, and no luck. See last commit from https://bitbucket.org/maho/tmpkh2 - to avoid situation that we run slightly different versions of libs, I made script install-and-run.sh - which create virtualenv, install deps there and run script. 

Look, that in your new_model_format branch, each frame shows something totally wrong. It shows proper frame, and additionally - some random fragment of other atlas sheet. 

So in summary: 
*  in master - unbatch/and batch after frame change make animation flickering on frames which are in different atlas sheets (not always visible), and always show error 
   ```Exception ValueError: 'list.remove(x): x not in list' in kivent_core.rendering.batching.BatchManager.remove_batch' ignored```
* in new_model_format branch - internal rebatching (or something else) gives displaying additional garbage over proper frames

**Comment by Kovak** [comment]
Can you include the error log you are getting on the new_model_format branch?

**Comment by mahomahomaho** [comment]
W dniu 09.06.2015 o 03:52, Kovak pisze:
> Can you include the error log you are getting on the new_model_format
> branch?

No errors, only bad display.

It looks like new_model_branch always show proper frame and also junk
from other sheet, while master branch sometimes show junk instead of one
frame when sheet changed (and error on console).

I have no idea if they are related, but it's possible.

**Comment by Kovak** [comment]
Can you share a minimal example that reproduces this behavior. I do not quite understand what you mean by your description. 

What you should do is attach some code that contain an atlas that behave the way you are saying, and a simple example code that uses the atlas to cause the behavior.

**Comment by mahomahomaho** [comment]
W dniu 09.06.2015 o 20:37, Kovak pisze:
> Can you share a minimal example that reproduces this behavior. I do not
> quite understand what you mean by your description.
> 
> What you should do is attach some code that contain an atlas that behave
> the way you are saying, and a simple example code that uses the atlas to
> cause the behavior.

I already did it, but looks that I forgot to mention it :) :

1. hg clone https://bitbucket.org/maho/tmpkh2/
2. cd tmpkh2
3. bash install-and-run.sh

assuming that you use linux and you have all build dependencies of kivy,
kivent, and cymunk - it will install everything in virtualenv and then
run minimal example.

**Comment by Kovak** [comment]
This is not a minimal example, and it makes it difficult to actually debug the actual issue.

A minimal example would contain ONLY the code necessary to reproduce the behavior, and absolutely NOTHING else. Nothing but a single py and a single kv file, no install scripts, no extra infrastructure from your game, just the single issue we are trying to actually debug right now. As it stands khamster.py does not even contain the code causing the behavior, meaning I need to dig through your import structure to get any further.

**Comment by mahomahomaho** [comment]
W dniu 09.06.2015 o 21:45, Kovak pisze:
> This is not a minimal example, and it makes it difficult to actually
> debug the actual issue.
> 
> A minimal example would contain ONLY the code necessary to reproduce the
> behavior, and absolutely NOTHING else. Nothing but a single py and a
> single kv file, no install scripts, no extra infrastructure from your
> game, just the single issue we are trying to actually debug right now.
> As it stands khamster.py does not even contain the code causing the
> behavior, meaning I need to dig through your import structure to get any
> further.

Ok, I will try to make such one

**Comment by mahomahomaho** [comment]
Ok, minimal example prepared. 

1. install kivent new_model_format branch  and kivy add_get_includes branches
2. clone repo from https://bitbucket.org/maho/tmpkh2/ - there is one .py, one .kv and one atlas, where each frame is in different atlas "sheet". 
3. run python khamster.py and:

Result: 
 a. error message goes to terminal every 2 frames at beginning, and next, every frame
 b. frames flickers at change, not every change, not always at the same frames, but it's noticeable at my machine, 

and log is 
```
 maho@dlaptop:/tmp/tmpkh2$ python khamster.py 
 Purge log fired. Analysing...
 Purge finished!
[INFO              ] [Logger      ] Record log in /home/maho/.kivy/logs/kivy_15-06-22_6.txt
[INFO              ] [Kivy        ] v1.9.1-dev
[INFO              ] [Python      ] v2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2]
[INFO              ] [Factory     ] 175 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <3.0 Mesa 10.3.2>
[INFO              ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO              ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Sandybridge Mobile >
[INFO              ] [GL          ] OpenGL parsed version: 3, 0
[INFO              ] [GL          ] Shading version <1.30>
[INFO              ] [GL          ] Texture max size <8192>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Shader      ] Read <assets/glsl/positionrotateshader.glsl>
[ERROR             ] [GameSystem  ] System_id: cymunk_physics not attached retrying in 1 sec. If you see this error once or twice, we are probably just waiting on the KV file to load. If you see it a whole bunch something is probably wrong. Make sure all systems are setup properly.
[INFO              ] [ProbeSysfs  ] device match: /dev/input/event14
[INFO              ] [MTD         ] Read event from </dev/input/event14>
[INFO              ] [Base        ] Start application main loop
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
     self.run()
   File "/usr/lib/python2.7/threading.py", line 763, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/home/maho/.virtualenvs/kivent2-newmodel/local/lib/python2.7/site-packages/kivy/input/providers/mtdev.py", line 197, in _thread_run
     _device = Device(_fn)
   File "/home/maho/.virtualenvs/kivent2-newmodel/local/lib/python2.7/site-packages/kivy/lib/mtdev.py", line 131, in __init__
     self._fd = os.open(filename, os.O_NONBLOCK | os.O_RDONLY)
 OSError: [Errno 13] Permission denied: '/dev/input/event14'

[INFO              ] [KivEnt      ] Vertex Format: vertex_format_4f registered. Size per vertex is: 16. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False)].
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_7f registered. Size per vertex is: 28. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False), ('rot', 1, 'float', 16, False), ('center', 2, 'float', 20, False)].
[INFO              ] [KivEnt      ] Vertex Format: vertex_format_8f registered. Size per vertex is: 32. Format is [('pos', 2, 'float', 0, False), ('uvs', 2, 'float', 8, False), ('vColor', 4, 'float', 16, False)].
[INFO              ] [KivEnt      ] Batches for canvas: <kivy.graphics.instructions.RenderContext object at 0x7f168ef48350> will have 9362 verts and 131072 indices.VBO will be 256 in KiB per frame with 40 total vbos, an estimated 2340 enities fit in each batch with 4 verts per entity
[INFO              ] [KivEnt      ] rotate_renderer allocated 22524 KiB
[INFO              ] [KivEnt      ] rotate allocated 160 KiB
[INFO              ] [KivEnt      ] cymunk_physics allocated 784 KiB
[INFO              ] [KivEnt      ] position allocated 236 KiB
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_4f. 75 KiB was reserved for vertices, fitting a total of 4800. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_7f. 75 KiB was reserved for vertices, fitting a total of 2742. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] Model Manager reserved space for vertex format: vertex_format_8f. 75 KiB was reserved for vertices, fitting a total of 2400. 25 KiB was reserved for indices fitting a total of 12800.
[INFO              ] [KivEnt      ] We will need 24708 KiB for game, we have 102400 KiB
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
 Exception ValueError: 'list.remove(x): x not in list' in 'kivent_core.rendering.batching.BatchManager.remove_batch' ignored
[INFO              ] [Base        ] Leaving application in progress...
```

**Comment by Kovak** [comment]
Thanks very much for taking the time to put this together. I am on vacation
and away from the computer for the next week, but will take a look when I
get home

**Comment by Kovak** [comment]
Good find on this one @mahomahomaho 

I just pushed a change to the new_model_format branch that should fix your problem. Let me know if it works for you. We were not properly reseting the tex_key for a batch that was reused.

**Comment by mahomahomaho** [comment]
W dniu 01.07.2015 o 03:50, Kovak pisze:
> Good find on this one @mahomahomaho <https://github.com/mahomahomaho>
> 
> I just pushed a change to the new_model_format branch that should fix
> your problem. Let me know if it works for you. We were not properly
> reseting the tex_key for a batch that was reused.
> 

Looks like issue is fixed, because I see no more error messages in logs.
However - it still flickers in my game, but not in case, so it's
probably bug in my code.
