### ISSUE TITLE
Cython compilation error when installing Kivent on Ubuntu 15.04

### ISSUE THREAD

**Issue by oddbitdev** [kivy/kivent#71]
So I thought it was about time getting back into Python game development and tried installing Kivent on a fresh Ubuntu install, but it fails with cython errors:

Cythonizing kivent_core/rendering/cmesh.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        self._batch = batch

    def __dealloc__(self):
        self._batch.clear_frames()

    cdef void apply(self):
        ^
------------------------------------------------------------

kivent_core/rendering/cmesh.pyx:19:9: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
    cdef str group
    cdef InstructionGroup parent
    cdef object __weakref__
    cdef object __proxy_ref

    cdef int apply(self) except -1
                 ^
------------------------------------------------------------

/usr/local/lib/python2.7/dist-packages/kivy/graphics/instructions.pxd:29:18: Previous declaration is here
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    extensions, core_modules)
  File "setup.py", line 84, in build_extensions_for_modules_cython
    return cythonize(ext_list)
  File "/home/oddbit/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 865, in cythonize
    cythonize_one(*args[1:])
  File "/home/oddbit/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: kivent_core/rendering/cmesh.pyx

Now, kivy itself works just fine (except it cannot find a clipboard provider, but that's a minor issue), and installing cymunk seemes to have worked (with a lot of warnings, but from what I remember from the last time when I got kivent to work, that's normal)

I've tried using both cython 0.21 and 0.22, same result. Any help would be greatly appreciated cause I really want to see some games made with kivy/kivent.

**Comment by Kovak** [comment]
It looks like you are compiling with the latest master kivy?

I have not updated to reflect the call signature changes that were made this week yet. I'll get it done pretty soon, in the meantime you should be able to build with kivy's stable branch. You could also update the call signature in cmesh if you want to use master.

**Comment by oddbitdev** [comment]
Hi, changing the signature worked, thanks for the help. Given the workaround and that you'll update the branch, I guess I will close the issue.
