### ISSUE TITLE
Examples 5 & 6: Clicking directly on asteroid doesn't grab it (grab area shifted right?)

### ISSUE THREAD

**Issue by arlowhite** [kivy/kivent#72]
The grab area for the asteroids doesn't seem to align with the visual. The actual grab area seems to be shifted to the right a bit.

**Comment by Kovak** [comment]
Hi can you give the fix_touch_collision branch a go, I think it should fix the issue. https://github.com/kivy/kivent/tree/fix_touch_collision

**Comment by arlowhite** [comment]
Yeah, that fixed it.
