### ISSUE TITLE
kivent instalation error in compilation 

### ISSUE THREAD

**Issue by Oussama-dev** [kivy/kivent#75]
i have used `sudo python setup.py build_ext install` to compile ''/KivEnt/modules/core''
and it agaves me : 
` in file included from kivent_core/rendering/frame_objects.c:239:0:
kivent_core/rendering/gl_redirect.h:34:26: fatal error: GLES2/gl2.h: No such file or directory
 #   include <GLES2/gl2.h>`
i managed to fix that by removing that section from the file "gl_redirect.h"
but now i have this problem : 
`kivent_core/rendering/frame_objects.c:469:3: error: unknown type name ‘GLuint’`
`   GLuint type;`
`    ^`
`kivent_core/rendering/frame_objects.c:545:3: error: unknown type name ‘GLuint’`
`   GLuint id;`
`    ^
 `

**Comment by Kovak** [comment]
Hi,

This is something I'm in the process of fixing with the kivy
add_get_includes branch and the kivent new_model_format branch, if you want
to get it to work in the meantime you should add the gles/gl2.h directory
from kivy into the kivent_core/rendering directory

**Comment by Oussama-dev** [comment]
OK thanx , but what about 

`kivent_core/rendering/frame_objects.c:469:3: error: unknown type name ‘GLuint’`
`   GLuint type;`
`    ^`
`kivent_core/rendering/frame_objects.c:545:3: error: unknown type name ‘GLuint’`
`   GLuint id;`
`    ^
 `
and i really appreciate your work, this is awesome project keep it up :) .

**Comment by Kovak** [comment]
This means we aren't linking fully with kivy's gl headers as its not
finding the gl types. Can you post a more full log?

**Comment by Oussama-dev** [comment]
Hi, even if i added the gles/gl2.h directory from kivy (kivy/tools/gles_compat) into the kivent_core/rendering directory it didn't work. 
and i think the linking problem shows because i removed the ```# include <GLES2/gl2.h>``` from `gl_redirect.h`
when i did removed that :
`kaybo@BOST:~/Downloads/kivent-master/modules/core$ sudo python setup.py build_ext install
[sudo] password for kaybo: `
`Compiling kivent_core/memory_handlers/block.pyx because it changed.`
`Compiling kivent_core/gameworld.pyx because it changed.`
`Compiling kivent_core/memory_handlers/indexing.pyx because it changed.`
`Compiling kivent_core/systems/gamemap.pyx because it changed.`
`Compiling kivent_core/memory_handlers/tests.pyx because it changed.`
`Compiling kivent_core/rendering/frame_objects.pyx because it changed.`
`Compiling kivent_core/systems/rotate_systems.pyx because it changed.`
`Compiling kivent_core/systems/gamesystem.pyx because it changed.`
`Compiling kivent_core/memory_handlers/pool.pyx because it changed.`
`Compiling kivent_core/systems/scale_systems.pyx because it changed.`
`Compiling kivent_core/systems/staticmemgamesystem.pyx because it changed.`
`Compiling kivent_core/rendering/batching.pyx because it changed.`
`Compiling kivent_core/rendering/cmesh.pyx because it changed.`
`Compiling kivent_core/memory_handlers/membuffer.pyx because it changed.`
`Compiling kivent_core/rendering/vertmesh.pyx because it changed.`
`Compiling kivent_core/rendering/vertex_formats.pyx because it changed.`
`Compiling kivent_core/entity.pyx because it changed.`
`Compiling kivent_core/managers/resource_managers.pyx because it changed.`
`Compiling kivent_core/memory_handlers/zone.pyx because it changed.`
`Compiling kivent_core/memory_handlers/zonedblock.pyx because it changed.`
`Compiling kivent_core/uix/gamescreens.pyx because it changed.`
`Compiling kivent_core/systems/gameview.pyx because it changed.`
`Compiling kivent_core/rendering/vertex_format.pyx because it changed.`
`Compiling kivent_core/memory_handlers/utils.pyx because it changed.`
`Compiling kivent_core/systems/color_systems.pyx because it changed.`
`Compiling kivent_core/uix/cwidget.pyx because it changed.`
`Compiling kivent_core/systems/position_systems.pyx because it changed.`
`Compiling kivent_core/rendering/fixedvbo.pyx because it changed.`
`Compiling kivent_core/rendering/gl_debug.pyx because it changed.`
`Compiling kivent_core/managers/system_manager.pyx because it changed.`
`Compiling kivent_core/systems/renderers.pyx because it changed.`
`Compiling kivent_core/managers/entity_manager.pyx because it changed.`
`Cythonizing kivent_core/entity.pyx`
`Cythonizing kivent_core/gameworld.pyx`
`Cythonizing kivent_core/managers/entity_manager.pyx`
`Cythonizing kivent_core/managers/resource_managers.pyx`
`Cythonizing kivent_core/managers/system_manager.pyx`
`Cythonizing kivent_core/memory_handlers/block.pyx`
`Cythonizing kivent_core/memory_handlers/indexing.pyx`
`Cythonizing kivent_core/memory_handlers/membuffer.pyx`
`Cythonizing kivent_core/memory_handlers/pool.pyx`
`Cythonizing kivent_core/memory_handlers/tests.pyx`
`Cythonizing kivent_core/memory_handlers/utils.pyx`
`Cythonizing kivent_core/memory_handlers/zone.pyx`
`Cythonizing kivent_core/memory_handlers/zonedblock.pyx`
`Cythonizing kivent_core/rendering/batching.pyx`
`Cythonizing kivent_core/rendering/cmesh.pyx`
`Cythonizing kivent_core/rendering/fixedvbo.pyx`
`Cythonizing kivent_core/rendering/frame_objects.pyx`
`Cythonizing kivent_core/rendering/gl_debug.pyx`
`Cythonizing kivent_core/rendering/vertex_format.pyx`
`Cythonizing kivent_core/rendering/vertex_formats.pyx`
`Cythonizing kivent_core/rendering/vertmesh.pyx`
`Cythonizing kivent_core/systems/color_systems.pyx`
`Cythonizing kivent_core/systems/gamemap.pyx`
`Cythonizing kivent_core/systems/gamesystem.pyx`
`Cythonizing kivent_core/systems/gameview.pyx`
`Cythonizing kivent_core/systems/position_systems.pyx`
`Cythonizing kivent_core/systems/renderers.pyx`
`Cythonizing kivent_core/systems/rotate_systems.pyx`
`Cythonizing kivent_core/systems/scale_systems.pyx`
`Cythonizing kivent_core/systems/staticmemgamesystem.pyx`
`Cythonizing kivent_core/uix/cwidget.pyx`
`Cythonizing kivent_core/uix/gamescreens.pyx`
`running build_ext`
`building 'kivent_core.memory_handlers.block' extension`
`creating build`
`creating build/temp.linux-x86_64-2.7`
`creating build/temp.linux-x86_64-2.7/kivent_core`
`creating build/temp.linux-x86_64-2.7/kivent_core/memory_handlers`
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c kivent_core/memory_handlers/block.c -o build/temp.linux-x86_64-2.7/kivent_core/memory_handlers/block.o -std=c99 -ffast-math`
`creating build/lib.linux-x86_64-2.7`
`creating build/lib.linux-x86_64-2.7/kivent_core`
`creating build/lib.linux-x86_64-2.7/kivent_core/memory_handlers`
`x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/kivent_core/memory_handlers/block.o -o` `build/lib.linux-x86_64-2.7/kivent_core/memory_handlers/block.so`
`building 'kivent_core.gameworld' extension`
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c kivent_core/gameworld.c -o build/temp.linux-x86_64-2.7/kivent_core/gameworld.o -std=c99 -ffast-math`
`x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/kivent_core/gameworld.o -o build/lib.linux-x86_64-2.7/kivent_core/gameworld.so`
`building 'kivent_core.memory_handlers.indexing' extension`
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c kivent_core/memory_handlers/indexing.c -o build/temp.linux-x86_64-2.7/kivent_core/memory_handlers/indexing.o -std=c99 -ffast-math`
`x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/kivent_core/memory_handlers/indexing.o -o` `build/lib.linux-x86_64-2.7/kivent_core/memory_handlers/indexing.so`
`building 'kivent_core.systems.gamemap' extension`
`creating build/temp.linux-x86_64-2.7/kivent_core/systems`
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c kivent_core/systems/gamemap.c -o build/temp.linux-x86_64-2.7/kivent_core/systems/gamemap.o -std=c99 -ffast-math`
`creating build/lib.linux-x86_64-2.7/kivent_core/systems`
`x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/kivent_core/systems/gamemap.o -o` `build/lib.linux-x86_64-2.7/kivent_core/systems/gamemap.so`
`building 'kivent_core.memory_handlers.tests' extension`
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c kivent_core/memory_handlers/tests.c -o build/temp.linux-x86_64-2.7/kivent_core/memory_handlers/tests.o -std=c99 -ffast-math`
`x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/kivent_core/memory_handlers/tests.o -o` `build/lib.linux-x86_64-2.7/kivent_core/memory_handlers/tests.so`
`building 'kivent_core.rendering.frame_objects' extension`
`creating build/temp.linux-x86_64-2.7/kivent_core/rendering`
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c kivent_core/rendering/frame_objects.c -o build/temp.linux-x86_64-2.7/kivent_core/rendering/frame_objects.o -std=c99 -ffast-math`
`kivent_core/rendering/frame_objects.c:469:3: error: unknown type name ‘GLuint’`
`   GLuint type;`
`   ^`
`kivent_core/rendering/frame_objects.c:545:3: error: unknown type name ‘GLuint’`
`   GLuint id;`
`   ^`
`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by Kovak** [comment]
You probably need to duplicate the headers in several places, you
definitely shouldn't remove the include from gl_redirect. Notice how there
are several headers included through the codebase, the gles2 probably needs
to be everywhere the other headers are.

I'm on vacation at the moment but when I get home next week ill prioritize
getting the kivy patch for the includes accepted and getting the changes to
make the header duplication unnecessary merged into master

**Comment by Oussama-dev** [comment]
thank you man i know that was stupid, well i will try to make it work by my self until then, i will learn more about c/c++ ;) .
i wish you a good vacation.

**Comment by Oussama-dev** [comment]
Hello, is there any updates about this issue, thanx.

**Comment by Kovak** [comment]
You should be able to try the master branch of Kivy + the new_model_format branch of KivEnt as the includes should properly import in these branches.

**Comment by Oussama-dev** [comment]
Hi again, i tried that and i got this : 
`[INFO   ] [Logger      ] Record log in /home/kaybo/.kivy/logs/kivy_15-07-29_0.txt`
`[INFO   ] [Kivy        ] v1.9.0`
`[INFO   ] [Python      ] v2.7.9 (default, Apr  2 2015, 15:33:21)` 
`[GCC 4.9.2]`
   `Traceback (most recent call last):`
        `File "setup.py", line 105, in <module>`
             `extensions, core_modules)`
        `File "setup.py", line 83, in build_extensions_for_modules_cython`
            `include_dirs=kivy.get_includes())`
  `AttributeError: 'module' object has no attribute 'get_includes'`

**Comment by Kovak** [comment]
You are not using the master branch of Kivy, it does not work with the stable as get_includes was recently added.

**Comment by Oussama-dev** [comment]
I had a small issue whit removing kivy(stable), so it works now but not all the modules are,
the examples "0, 1, 2, 4, 5, 6, 8 " works just fine,
 but the others not, example:
`kaybo@BOST:~/Documents/kivent-new_model_format/examples/7_star_fade$ python main.py`
`[INFO   ] [Logger      ] Record log in /home/kaybo/.kivy/logs/kivy_15-07-29_32.txt`
`[INFO   ] [Kivy        ] v1.9.1-dev`
`[INFO   ] [Python      ] v2.7.9 (default, Apr  2 2015, 15:33:21) `
`[GCC 4.9.2]`
`[INFO   ] [Factory     ] 176 symbols loaded`
`[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)`
`[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)`
`[WARNING] [WinPygame   ] Video: failed (multisamples=2)`
`[WARNING] [WinPygame   ] trying without antialiasing`
`[INFO   ] [GL          ] OpenGL version <2.1 Mesa 10.5.2>`
`[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>`
`[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Ironlake Mobile >`
`[INFO   ] [GL          ] OpenGL parsed version: 2, 1`
`[INFO   ] [GL          ] Shading version <1.20>`
`[INFO   ] [GL          ] Texture max size <8192>`
`[INFO   ] [GL          ] Texture max units <16>`
`[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked`
`[INFO   ] [OSC         ] using <multiprocessing> for socket`
`Traceback (most recent call last):`
   `File "main.py", line 11, in <module>`
     `from kivent_core.managers.resource_managers import (texture_manager,` 
` ImportError: cannot import name model_manager`

**Comment by Kovak** [comment]
I'm still working on updating all of the examples to some of the changes in the new branch. This a working and not yet released branch so some stuff is not quite up to date.

**Comment by Oussama-dev** [comment]
OK so every thing is normal, i just have to discover how it works, by the way nice performance.
