### ISSUE TITLE
focus_entity stop working when map size changed

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/kivent#81]
When map size is set to window.root initially, and then changed to bigger size (eg. after level loaded, then focus entity stop working when window size changed). 

How to reproduce: 
* hg clone https://bitbucket.org/maho/tmpcase3
* cd tmpcase3 && python khamster.py
* you will see that camera is following hamster, 
* resize window (eg. maximize it)

SHOULD BE: camera should still follow hamster
IS: camera stop following hamster and sticks in left-top corner of the map.

**Comment by Kovak** [comment]
The repo linked to in this issue is no longer public. Looking through the code I didn't see anything obvious and wanted to take a look at replicating the issue.

**Comment by mahomahomaho** [comment]
oops, I forgot to make it public. now is public.

**Comment by Kovak** [comment]
You have map_size bound to root.size and do_scroll_lock to True for GameView. Your entity leaves the size of the map and so the camera stops going beyond it. Either turn do_scroll_lock to False or ensure that the character stays within the bounds of the map.

**Comment by mahomahomaho** [comment]
But I set map_size here: https://bitbucket.org/maho/tmpcase3/src/ac76865332cef871376124a9a7cc2a1e685d625f/game.py?at=default&fileviewer=file-view-default#game.py-36

So is no longer bound to root.size, I think ....

**Comment by Kovak** [comment]
It is still bound and so then when size changes, it is reupdated to size
instead of the value you set.

**Comment by mahomahomaho** [comment]
W dniu 15.09.2015 o 01:48, Kovak pisze:
> It is still bound and so then when size changes, it is reupdated to size
> instead of the value you set.

Ok, thanks. Then setting it to some fixed value solved my problem. No
bug then.
