### ISSUE TITLE
Loading the Assets in (Kivent-new model format)

### ISSUE THREAD

**Issue by Oussama-dev** [kivy/kivent#82]
I am trying to modify some of the old examples and make theme work in `Kivent-new model format`
and i can't solve this :

`Traceback (most recent call last):`
`   File "main.py", line 15, in <module>`
`     ModelManager.load_textured_rectangle(4, 7., 7., 'star1', 'star1-4')`
` TypeError: descriptor 'load_textured_rectangle' requires a` `'kivent_core.managers.resource_managers.ModelManager' object but received a 'int'`

**Comment by Kovak** [comment]
it looks like you are referencing the definition of ModelManager and not an instance.  You should use the model_manager of your GameWorld instance. I will be updating these examples over the next few days.

**Comment by Oussama-dev** [comment]
So, i was looking in the wrong place, i thought that you changed the name from model_manager to ModelManager since it was belong to resource_managers module .
and for the examples and the documentation it will be life saving for me, i am lost.
especially with the memory management part.
