### ISSUE TITLE
touch error 

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/kivent#96]
When run game with most recent code (your today's push to master), I get this traceback on android right after I touch the screen:

```
I/python  (14639): [INFO              ] [Base        ] Leaving application in progress...
I/python  (14639):  Traceback (most recent call last):
I/python  (14639):    File "/home/maho/workspace/khamster/src/buildozer/.buildozer/android/app/main.py", line 117, in <module>
I/python  (14639):    File "/home/maho/workspace/khamster/src/buildozer/p4a/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 828, in run
I/python  (14639):    File "/home/maho/workspace/khamster/src/buildozer/p4a/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
I/python  (14639):    File "/home/maho/workspace/khamster/src/buildozer/p4a/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 401, in mainloop
I/python  (14639):    File "/home/maho/workspace/khamster/src/buildozer/p4a/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 288, in _mainloop
I/python  (14639):    File "/home/maho/workspace/khamster/src/buildozer/p4a/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 330, in idle
I/python  (14639):    File "/home/maho/workspace/khamster/src/buildozer/p4a/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 315, in dispatch_input
I/python  (14639):    File "/home/maho/workspace/khamster/src/buildozer/p4a/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 262, in post_dispatch_input
I/python  (14639):  AttributeError: 'NoneType' object has no attribute 'push'
I/python  (14639): Python for android ended.
```

**Comment by mahomahomaho** [comment]
The same eg in example 6_controlling_the_viewing_area - try to click "Draw some stuff" button. (hopefully this means that I don't need to write testcase ;) )

**Comment by mahomahomaho** [comment]
I just realized that there is no kivent int traceback, so I'm not sure if it's kivy or kivent error. 

However, if I stay in this revision: e0d480a1d1546af024fb04c1688247b2c33b7c30 - then there is no such error.

**Comment by Kovak** [comment]
Seems like maybe there was a change in the way Kivy handles touch, I dunno, I need to investigate further.

**Comment by mahomahomaho** [comment]
I have bisected kivent and seems that problem occurs in changeset be4530d4c4e857fe2f5c8ca2dd9b36e9e3405d1e

**Comment by Kovak** [comment]
The big problem here is that this was just an update from the old definition of Widget to the current definition of Widget: https://github.com/kivy/kivy/blob/master/kivy/uix/widget.py#L297

This code is not unique to kivent, every widget have it.

**Comment by mahomahomaho** [comment]
See my PR - as mentioned in commit log, I have no idea what does it mean, I just found it by commenting line by line. 

UPDATE: I think I know why such change is neccesary. Cwidget has property _context, so hasattr(self, '_context') is always true.

**Comment by Kovak** [comment]
thanks for tracking that down!
